### ISSUE TITLE
Not seeing the new switches from 1.0 update

### ISSUE THREAD

**Issue by mattson16** [nicoduj/homebridge-deebotEcovacs#13]
I am now on 1.1 and you are on a roll! Are these switches available now or are they still in development. I read the change log and it appears i should be seeing 4 different switches for the vacuum.

**Comment by nicoduj** [comment]
still fixing, but you will have to clean your cache for them to appear. (use cleanCache option )
![IMG_3FB04F79DAAB-1](https://user-images.githubusercontent.com/19813688/79793267-8e862600-8350-11ea-82b7-79110bdeb028.jpeg)
![IMG_3FB04F79DAAB-2](https://user-images.githubusercontent.com/19813688/79793273-934ada00-8350-11ea-95ab-ac57bb8d529d.jpeg)

**Comment by mattson16** [comment]
what is the best way to use cleanCache?

**Comment by nicoduj** [comment]
add option in your config.json "cleanCache":true on tou plugin config section.
Restart homebridge
Remove option in your config or set it to false.

0.1.2 on its way ... will stay there for tonight ;p

**Comment by mattson16** [comment]
Would you be able to help show me where exactly “cleancache”:true is placed in the config file?

**Comment by nicoduj** [comment]
> Would you be able to help show me where exactly “cleancache”:true is placed in the config file?

like this :

```json
"platforms": [
  {
    "platform": "HomebridgeDeebotEcovacs",
    "email": "toto@titi.com",
    "password": "toto",
    "countryCode" : "FR",
    "cleanCache": true
  }
]
```

**Comment by nicoduj** [comment]
@mattson16 is it ok now ?

**Comment by mattson16** [comment]
i've got it fixed now. i ended up having to set up the homebridge server again but it's all good now.

**Comment by nicoduj** [comment]
MAy I ask if everything is working with your deebot ?
