### ISSUE TITLE
Help-issue since you pulled the plugin

### ISSUE THREAD

**Issue by banjobanjobanjo** [nicoduj/homebridge-deebotEcovacs#15]
When the plugin was pulled, I had removed and tried to reinstall it. Somehow, now, it is stuck in limbo. I can’t install or uninstall any plugins on hooks/homebridge. I get the following error:

Error while executing:
npm ERR!
 /usr/bin/git ls-remote -h -t https://github.com/nicoduj/sucks.js.git
npm ERR! 
npm ERR!
 remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/nicoduj/sucks.js.git/'
npm ERR! 
npm ERR! exited with error code: 128

Please help! What can I do to remove this dependency? Your plugin is no longer installed, but it keeps trying to connect. I really really don’t want to rebuild the whole home bridge setup! Thank you.

**Comment by banjobanjobanjo** [comment]
To be clear, this error comes up no matter what plugin I try to install or uninstall. It’s holding my setup hostage.

**Comment by nicoduj** [comment]
Hi,

first off all, sorry for that, I did not anticipate such a mess with npm while doing so. Even if this plugin is a pre-release, should have been more careful.

Follow those steps to try to resolve the problem : 
- in your homebridge directory (/homebridge), edit package.json and remove the plugin line
- in this same directory, do the following command : 
```bash
npm prune
```
- check npm state after
```bash
npm list
```
- if you still see a version of deebotecovacs (with X version you see) , do this 
```bash
npm uninstall --save homebridge-deebotecovacs@0.0.X
```
- restart homebridge

I think that is what I did to solve the issue. Let me know, and feel free to post results of those commands if you need further help.

Once again, sorry !
