### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by LucaSteven** [nicoduj/homebridge-deebotEcovacs#18]
Hi. i have home bridge 1.0.4 on raspberry and have problems installing your plugin. 

pi@homebridge:/var/lib/homebridge $ npm install -g homebridge-deebotecovacs
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-04T13_50_57_254Z-debug.log
pi@homebridge:/var/lib/homebridge $

**Comment by nicoduj** [comment]
Hi, it is a permission issue since you are trying to install globally.(-g)
May I ask how you have installed other plugins ? I would suggest you use configUI also to simplify all this process. 
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

You could definitely use a sudo chown command, but in my experience missing with permission might lead to unexpected beahvior, dependeing how you installed everything 

sudo chown -R $USER /usr/local/lib/node_modules

Let me know

**Comment by LucaSteven** [comment]
Hi, thru the graphic interface , plugin, search for deebot, then install from there  as I installed the other two plug-ins I have . Thank you 

Enviado desde mi iPhone

**Comment by nicoduj** [comment]
Regular homebridge or hoobs ?  You can try to run it as sudo but on regular homebridge should not be neeeded

**Comment by LucaSteven** [comment]
Regular 

Enviado desde mi iPad Pro

**Comment by nicoduj** [comment]
ok, try to add permission to the user you use in homebridge to the directory : usr/local/lib/node_modules

**Comment by LucaSteven** [comment]
Sorry, I’m new to this lol …. How can I add permissions ?

**Comment by nicoduj** [comment]
https://flaviocopes.com/npm-fix-missing-write-access-error/

**Comment by LucaSteven** [comment]
pi@homebridge:/var/lib/homebridge $ sudo chown -R $USER /usr/local/lib/node_modules
pi@homebridge:/var/lib/homebridge $ sudo -E -n npm install homebridge-deebotecovacs@latest
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js

> canvas@2.6.1 install /var/lib/homebridge/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.2 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/lib/homebridge/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/var/lib/homebridge/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /var/lib/homebridge/node_modules/canvas
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/lib/homebridge/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/lib/homebridge/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/lib/homebridge/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.97-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/var/lib/homebridge/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/lib/homebridge/node_modules/canvas
node-pre-gyp ERR! node -v v12.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/lib/homebridge/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/lib/homebridge/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN enoent ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No README data
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-10T08_29_37_813Z-debug.log
pi@homebridge:/var/lib/homebridge $

**Comment by nicoduj** [comment]
Canvs does not have pre build lib for your system and build does not work. Did you check you have the dep mentionned in readme ? 

apk add build-base cairo-dev jpeg-dev pango-dev giflib-dev librsvg-dev

**Comment by LucaSteven** [comment]
Hi Nicolas. Now I got adding the plug in to homebrigde but can’t add it to HomeKit. , appears as a bridge , adding the home bridge code but keeps in “adding”  then after minutes gives error connecting

**Comment by LucaSteven** [comment]
Sorry Nicolas, I added the vacuum to Homekit but… if I say “ turn on vacuum” it only beeps…. What is the instruction to make it start working?

**Comment by nicoduj** [comment]
It is because of the bip switch yes, can you try manually through home app ? There is a fan and 2 switches. I encourage you to rename the fan switch and use it with siri .

**Comment by nicoduj** [comment]
@LucaSteven is it ok ? I will try to make the fan service the primary service if possible, for me it is ok howeve hen I ask siri to turn it on / off, it sends on to both swithes.

**Comment by LucaSteven** [comment]
Hi , I deleted the plugin by now . Waiting for some upgrades . Thank you 

Enviado desde mi iPhone

**Comment by nicoduj** [comment]
ok, no problem. But I won't know what to upgrade then for you ! Will close this so :)
