### ISSUE TITLE
Failure connecting to ecovacs

### ISSUE THREAD

**Issue by strangeblue** [nicoduj/homebridge-deebotEcovacs#20]
Hi, thanks for this plugin.

When I run home bridge I get the following error:
[10/05/2020, 3:23:45 pm] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: getaddrinfo ENOTFOUND portal-oc.ecouser.net
[10/05/2020, 3:23:45 pm] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute

My account info is correct, country code AU.

Cheers

**Comment by nicoduj** [comment]
Hi, could you tell me which model you are using ? And share your conf please without personal info

**Comment by strangeblue** [comment]
I have a Deetbot 600.

Config file:

{
	"bridge": {
		"name": "Homebridge",
		"username": “XXXX,
		"pin": “XXXX"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},


	"platforms": [{
			"platform": "SensiboSky",
			"name": "Sensibo",
			"apiKey": “XXXX",
			"timeLapse": 5,
			"ai": false,
			"hideFan": true,
			"hideHumidity": true,
			"fixedState": "auto"
		},
		{
			"platform": "DeebotEcovacs",
			"email": “XXXX",
			"password": “XXXX",
			"countryCode": “AU"
		}
	]
}


Cheers,

Steve

**Comment by nicoduj** [comment]
Ok, it should work but was not tested as far as I know. However, it seems there is no ecovacs server for your continent

Could you try with another country, like FR

**Comment by strangeblue** [comment]
Tried that - it runs but then hangs on this:

[10/05/2020, 6:23:52 pm] [DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
[10/05/2020, 6:23:52 pm] [DeebotEcovacs] INFO - Discovered Deebot : e2001171391905060336

Stops there and never offers me a HomeKt code.

**Comment by nicoduj** [comment]
Don’t know what you mean by hangs there . It won’t offer a code since it is linked to your homebridge bridge . Did you check in your home app in default room ? 

You can try to launch in debug mode but in normal log you won’t have more info / log .

**Comment by nicoduj** [comment]
@strangeblue  Any news / success ? The accessory is linked to homebridge you won’t need a code it will be added automatically in default room

**Comment by strangeblue** [comment]
Yes thanks got it all sorted.

Sorry for the confusion I am still learning my way around Homebridge.

Thanks for your hard work.

**Comment by Soldiiier** [comment]
I am also getting the same error using Au country code. What is the solution?

**Comment by strangeblue** [comment]
Change it to FR. Works for me.

**Comment by Soldiiier** [comment]
Yes FR works for me. I also tried CN, but made no difference.
