### ISSUE TITLE
Question on fan direction selection

### ISSUE THREAD

**Issue by julien94800** [nicoduj/homebridge-deebotEcovacs#22]
Hello,
First, thanks for your job! As for harmony, it works great!
I have one question about the fan direction that seems to be used to select the cleaning mode (edge or auto). Is there a way in home app to know which one is selected? 
Furthermore, in the native Deebot app, I did not find any corresponding setting. Do you know which native option it modified?

Thanks in advance

**Comment by nicoduj** [comment]
Hi @julien94800 , I am glad that those plugins are helpfull :)

Concerning the fan direction, indeed it is to switch between auto and edge mode . The direction itself should indicate the mode (default auto : clockwise If I correctly remember) . Not sure it will work on all deebots models , in the app it is there :

![image](https://user-images.githubusercontent.com/19813688/82781357-df120700-9e59-11ea-85ba-78c8c368c25b.jpeg)

And thanks for the beers on PayPal ;)

**Comment by julien94800** [comment]
Hello @nicoduj ,
Thanks for your feedback. In my case, I only have the option below
![image](https://user-images.githubusercontent.com/22552386/82784345-a1fd4300-9e60-11ea-8fa0-6e9b30c7fadb.jpeg)

It is a DEEBOT 920. It seems that in home app, if I set the direction anti-clockwise nothing happens!
Is there a way to have an attribute in text that tells which mode is selected (maybe only visible on EVE app)?

**Comment by nicoduj** [comment]
Indeed edge mode is hard coded :) will try to improove this and add custom feature like you said !

**Comment by julien94800** [comment]
Thanks very much! To be honest I am not sure what could be the best way to show this in homekit and what could be done.
