### ISSUE TITLE
Customize what switches become active 

### ISSUE THREAD

**Issue by cmfrazier** [nicoduj/homebridge-deebotEcovacs#23]
Would it be possible to disable some of the switches/features within the plugin? For example, I would just like the Auto Clean switch and Motion Detection for an issues. So just 2 or 4 of the devices created by default.

**Comment by nicoduj** [comment]
yes, possible, adding to wish list :p

**Comment by forresthamilton** [comment]
Additionally, can the names of the switches be adjusted/changed? Instead of start/stop can it be clean/return to charge or Fan Speed instead of start/stop or am I missing something?
