### ISSUE TITLE
HomeKit unable to control Deebot after it enters sleep mode

### ISSUE THREAD

**Issue by tteuer** [nicoduj/homebridge-deebotEcovacs#27]
Hi there,

I have not been able to control my Deebot after it returns to the charger and enters the sleep mode. When I control any of the Deebot options in HomeKit, they will "turn on" and then turn off a while later – my Deebot doesn't respond at all.

When I start vacuuming from the Ecovacs app, the Deebot wakes up and vacuums as it should – and the icons all update to their appropriate status in HomeKit. I can control it via HomeKit after this, until it returns to the charger and goes back to sleep.

Any ideas?

**Comment by nicoduj** [comment]
Hi can you tell me what vaccumm model you are using  ? Do you see the same behavior with ecovacs app ? Is the deebot still connected on wifi while in standby ?

I would be interested into the logs when you try to wake it up while asleep.

**Comment by tteuer** [comment]
Hey there, I'm using a Deebot 900. It works just fine from the Ecovacs app. It will not wake up when using HomeKit though. Once I activate it with the Ecovacs app, HomeKit updates the status correctly and I am able to control it through HomeKit without any issues – until it docks to charge and eventually goes back to sleep. 

I would assume it's still connected to Wifi while in standby because it wakes up when using the Ecovacs app without any issue? 

How would I get you logs for when it is waking up? I don't see any status updates in my Homebridge logs.

**Comment by Nils89** [comment]
Have the same issue with deboot 950. 

But BIP is working fine

**Comment by tteuer** [comment]
I'm glad I'm not the only one it seems like...

**Comment by Nils89** [comment]
For me deebot 950, this was causing the wrong fan direction causing this. 
It was set to edge cleaning, which is not available, so change the direction to auto clean and it works perfect.

**Comment by tteuer** [comment]
That did it! Thank you so much. I wonder if there's anyone documentation could be provided about that? I'd been trying to figure out the difference between clockwise and counterclockwise and that must've caused the issue.

 Mine was set to "rotate clockwise" and did not work. Setting it to "counterclockwise" made it work as expected. 

I think the reason I was able to control it after I'd already started a cleaning cycle was because it was using the current/correct cleaning mode (auto).
