### ISSUE TITLE
Compatibility with raspberry pi?

### ISSUE THREAD

**Issue by nikollou** [nicoduj/homebridge-deebotEcovacs#35]
Hello,

thanks for your time and effort in developing this plugin! Have you by any chance verified if it works on a Pi?

I have setup homebridge on a Pi at my house and when I try to install deebotecovacs it seems like the install completes but then homebridge gets corrupt and the UI won't load anymore. I have tried this twice and I had the exact same outcome. 

I confirm that I have run the command to compile canvas based on the link you provided. 
`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

Just wondered if you have managed to get this to work on a pi. Happy to provide debug info if this is something you want to look into.

Nik

**Comment by nicoduj** [comment]
Hi, canvas should not be necessary anymore.

However, di not test on pi, but since canvas is not needed should be ok now.

**Comment by mrbungle64** [comment]
@nikollou @nicoduj 

The library definitely works on Raspberry Pi 3/4 (also with canvas).
I installed Homebridge on my Raspberry Pi 3B last week incl. deebotEcovacs plugin and it's working fine :+1:

**Comment by nikollou** [comment]
Ok thank you both, will give it another try since I must then be doing something wrong on my end.
Cheers,
Nik
