### ISSUE TITLE
New publish zone function

### ISSUE THREAD

**Issue by joeyski** [nicoduj/homebridge-deebotEcovacs#38]
Please clarify how the zones correlate to areas mapped in the Deebot app.  It appears that zones in the plugin can only be a numeric value and areas in the Deebot app cannot have custom numerical names to match (only default tags of kitchen, office, etc...).  Sorry for the silly question, but I can’t figure out how to publish a switch for mapped areas in the app (AKA zones in the plugin).  Thanks in advance!  Best, Joe

**Comment by nicoduj** [comment]
Hi, very diificult to say, since my deebot does not handle zones,I have only expose what there is in the js lib I am using. 

explained there I think : https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/spotArea

**Comment by nicoduj** [comment]
After reading a bit more carefully, might be the spot area feature, not  the custom area. will look deeper into this (ut not easy since as I said mine do not have those features)

**Comment by joeyski** [comment]
To test either scenario, I published switches by number and tried to activate them just to see where the robot might go.  The switch fails to start on all accounts (Zone 1, Zone 2, Zone 3, etc...) and no log entries are written or errors shown.

**Comment by nicoduj** [comment]
thank you, command I sent might still be wrong, will investigate

**Comment by joeyski** [comment]
Thanks!  Another interesting observation is that Siri Shortcuts seems to look for zones (same as the plugin) but none are found for the robot.  That is, when you try to create a shortcut the robot name is shown and can be selected.  But, shows no zones available from the app.  Not sure if it’s pertinent, but thought it might mean something to you and I’d mention...  Thanks again for your great work on this!  Cheers!  Joe

**Comment by nicoduj** [comment]
Please try with 1.3.2 that is coming, and let me know

**Comment by mrbungle64** [comment]
> Please clarify how the zones correlate to areas mapped in the Deebot app. It appears that zones in the plugin can only be a numeric value and areas in the Deebot app cannot have custom numerical names to match (only default tags of kitchen, office, etc...). Sorry for the silly question, but I can’t figure out how to publish a switch for mapped areas in the app (AKA zones in the plugin). Thanks in advance! Best, Joe

@joeyski 
I asume that you're using a 950 based model like Ozmo 920/950/T8, right?
I think that there's no easy way (for a user) to map the area numbers to the areas in Ecovacs App for these models.
But the area where the charging station is located should be number 0 and the areas next to this area should be 1,2,3 etc...

@nicoduj 
I will check if I can extend the interface so that you directly can get the numbers and names of spot areas.
You can also have a look at how it's implemented in the [ioBroker adapter](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/77959770aa9bc12ac8178a1ba4a3def425f8210b/main.js#L616).

**Comment by nicoduj** [comment]
@mrbungle64 thank you, I think my first imp was not good, should be better with latest one

**Comment by joeyski** [comment]
Yes - T8+ (BTW many thanks for updating to include!)
I will test 1.3.2 and report back

**Comment by joeyski** [comment]
1.3.2 observations - Battery status (charging/percentage) no longer reporting
No switches are published, regardless of functionality
Error log attached
![9ED461AC-C0B2-473E-AED2-BEB129FF85ED](https://user-images.githubusercontent.com/1403865/98980861-d1713c00-24e2-11eb-9745-ae45d3fd40f2.jpeg)

**Comment by nicoduj** [comment]
Can yu check your dep ? ecovacs-deebot@0.4.25 expected (npm list)

**Comment by mrbungle64** [comment]
> 1.3.2 observations - Battery status (charging/percentage) no longer reporting
> No switches are published, regardless of functionality
> Error log attached
> ![9ED461AC-C0B2-473E-AED2-BEB129FF85ED](https://user-images.githubusercontent.com/1403865/98980861-d1713c00-24e2-11eb-9745-ae45d3fd40f2.jpeg)

@nicoduj 

`hasEdgeCleaningMode()` function is currently not implemented for 950 based models, because it doesn't derive from `VacBot` class yet. Sorry ... 

Please use `!this.hasSpotAreaCleaningMode()` for now.

```javascript
    hasEdgeCleaningMode() {
        return (!this.hasSpotAreaCleaningMode());
    }
```

**Comment by nicoduj** [comment]
Ok, will do. It is the only one ? I also test the following : 
        this.log('INFO - Edge Cleaning  : ' + vacBot.hasEdgeCleaningMode());
        this.log('INFO - Spot Cleaning  : ' + vacBot.hasSpotCleaningMode());
        this.log('INFO - SpotArea Cleaning  : ' + vacBot.hasSpotAreaCleaningMode());
        this.log('INFO - CustomArea Cleaning  : ' + vacBot.hasCustomAreaCleaningMode());

**Comment by nicoduj** [comment]
(fix on its way)

**Comment by joeyski** [comment]
Sorry guys - this is getting a bit out of my league with technical stuff...  I'll do my best...  I don't know how to verify dep version, but guessing it auto updated on 1.3.1 because I gained T8+ functionality.  I had nothing before...  What else do you want me to check?

**Comment by nicoduj** [comment]
> Sorry guys - this is getting a bit out of my league with technical stuff... I'll do my best... I don't know how to verify dep version, but guessing it auto updated on 1.3.1 because I gained T8+ functionality. I had nothing before... What else do you want me to check?

Just try with 1.3.3 that is coming (as soon as travis will want to) :)

**Comment by mrbungle64** [comment]
> Ok, will do. It is the only one ? I also test the following :
> this.log('INFO - Edge Cleaning : ' + vacBot.hasEdgeCleaningMode());
> this.log('INFO - Spot Cleaning : ' + vacBot.hasSpotCleaningMode());
> this.log('INFO - SpotArea Cleaning : ' + vacBot.hasSpotAreaCleaningMode());
> this.log('INFO - CustomArea Cleaning : ' + vacBot.hasCustomAreaCleaningMode());

@nicoduj 
I implemeted these in 0.4.26. I'm also waiting for travis ;)

**Comment by nicoduj** [comment]
@mrbungle64 first finished ;p Will go back to theis function in a next version so , thank you :)

**Comment by nicoduj** [comment]
Hum, @mrbungle64 , only EdgeCleaning was missing or there was another one ?

**Comment by mrbungle64** [comment]
> Hum, @mrbungle64 , only EdgeCleaning was missing or there was another one ?

@nicoduj 
No, they all were missing for 950 based models.
So that's why I wanted to fix it as soon as possible ;)

0.4.26 is available now ;)
https://www.npmjs.com/package/ecovacs-deebot/v/0.4.26

**Comment by nicoduj** [comment]
ok, thx, updating by my side so ! (you were first so, I should have checked ;)

**Comment by nicoduj** [comment]
1.3.4 is available :)

**Comment by mrbungle64** [comment]
> Sorry guys - this is getting a bit out of my league with technical stuff... I'll do my best... I don't know how to verify dep version, but guessing it auto updated on 1.3.1 because I gained T8+ functionality. I had nothing before... What else do you want me to check?

@joeyski 
Can you please check again with homebridge-deebotecovacs 1.3.4?

**Comment by julien94800** [comment]
Hello,
Just tried with last version and now seems to work with spot area on 920 model!! Just need to find wich number correspond to which area and should be perfect! I will try to play more with it and let you know if something goes wrong
Thanks very much

**Comment by joeyski** [comment]
Works perfect now!  Battery status too.  The 0, 1, 2, 3 numeric values correspond to A, B, C, etc...  Last question is can we get map coordinates out of the app to use custom areas too?  Thanks again!  You guys are the best!!!

**Comment by nicoduj** [comment]
Will try to improve this by going deeper in the lib, I understand it is a bit rough for the moment, but like I said my zoom does not have those features so it is really blind coding :)

**Comment by joeyski** [comment]
Many thanks!!!  Homebridge lets you rename the areas anyway, so it's not a big deal as is.  Also, wondering if you guys have plans or know if it's possible to manually trigger the auto empty function...  The app dumped manual empty a few versions ago (don't know why?) and it would be awesome to get that function back via homebridge...

**Comment by julien94800** [comment]
Indeed did not find any way to get coordinates from the Ecovacs app. But as it now fully works with spotarea, even if some sub zones are needed, it would be easier to create them in the app and then use it in homebridge with spot

Thanks again Nicolas!
Really nice job

**Comment by mrbungle64** [comment]
> ... Last question is can we get map coordinates out of the app to use custom areas too?...

@joeyski 
Yes, the library is able to get the coordinates of the custom area function, but it has to be implemeted in homebridge-deebotecovacs first, so that you maybe have to be patient ;)

@nicoduj 
There's an event in the library `LastUsedAreaValues`. You can use it to get that values.
