### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by Salsalove** [nicoduj/homebridge-deebotEcovacs#4]
here the log:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-deebotEcovacs - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-deebotEcovacs@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by nicoduj** [comment]
Hi, as mentionned in the readme, this plugin is a work in progress , and does not work at all for the moment !

**Comment by nicoduj** [comment]
@Salsalove if you are interested, I have a released a frist beta version, that works bascially for my ozmo Slim 10. Still a lot of work to do however, might crash and not be always accurate (and functions are limited)!
