### ISSUE TITLE
Set characteristics

### ISSUE THREAD

**Issue by carlosgamezvillegas** [nicoduj/homebridge-deebotEcovacs#41]
Hello guys, thank you so much for this plug in, I love it having it in my Home. 

I have one request regarding the characteristics set on the plug-in. Could you add “Model”, “Manufacturer” and “Serial Number”  to the settings so we can change them manually? Right now when you try to see the details of the vacuum in HomeKit it says “eco-ng” for manufacturer and nothing for the serial number. I have tried to change the .setCharacteristics on the js but it doesn’t seem to work. I have done that with other plugins but I can’t make this one work.

Thanks,

**Comment by nicoduj** [comment]
Added model in latest release.
