### ISSUE TITLE
No possibility of mapping several SpotAreas

### ISSUE THREAD

**Issue by Tins612** [nicoduj/homebridge-deebotEcovacs#43]
Good morning I'm new here and did a little homebridge research last week. Installation of the Homebridge according to the instructions from the forum worked. Now the Homebridge is running and I have worked on the Homebridge Deebotecovacs Plugin v1.4.1 for my Deebot robot. I see the autostart, suction power, start / stop and bip switches. Unfortunately I can't manage the SpotAreas. In the plugin settings you have to separate the spot areas with an apostrophe. However, my robot has two cards, one in the apartment and one in the basement. I would like to have individual rooms displayed for the apartment so that I can control them specifically. I only ever get the SpotArea0 displayed. As in the description, I have separated the SpotAreas with commas or in quotation marks. Unfortunately all without success. My robot is the Ozmo 950 model
About Help I would be happy.

Greetings Tins

translated with google translator, so maybe not perfect English

**Comment by Tins612** [comment]
![image](https://user-images.githubusercontent.com/74071600/101460291-b35bf780-3939-11eb-89c3-4d50da10845e.png)

**Comment by julien94800** [comment]
Hello,

Did you try something like "0","1","2" ?

**Comment by Tins612** [comment]
yes i tried too. Unfortunately without success. Only SpotArea 0 is always displayed

![image](https://user-images.githubusercontent.com/74071600/101461214-db982600-393a-11eb-8283-98fcd9143a8f.png)

![image](https://user-images.githubusercontent.com/74071600/101461319-fbc7e500-393a-11eb-8369-c6ea6b677741.png)

**Comment by julien94800** [comment]
Could you please share how it is written in your config file?

**Comment by Tins612** [comment]
![image](https://user-images.githubusercontent.com/74071600/101462341-6b8a9f80-393c-11eb-8a31-c9c4e0086914.png)

**Comment by julien94800** [comment]
From my side it is like this and it works

 "publishSpotAreaSwitches": [
                "0",
                "1",
                "2,3"
            ],

**Comment by Tins612** [comment]
I see the separation doesn't fit. Do I have to adjust this manually?

**Comment by julien94800** [comment]
Please try to update it manually yes in the same way I shared 
Could be linked to an update of homebridgeUI

**Comment by Tins612** [comment]
It works perfectly now. Many thanks

Which card does the SpotArea refer to? On the first map created or how is a SpotArea of another map controlled?

**Comment by julien94800** [comment]
You are welcome. All thanks should go to the plug-in creator!
It refers to the current active map in the app. Did not find any way to manage several maps from the plug-in but not really needed from my side. Too much difficult I would say

**Comment by Tins612** [comment]
OK thanks. The main card is enough for me too. Thanks again

**Comment by julien94800** [comment]
Hello @nicoduj 
I will let you close the issue if it is ok for everyone. 
We could try to update guideline for this but no real idea on how to improve it

Have a nice day everyone

**Comment by nicoduj** [comment]
Hi,

thanks for the support @julien94800  :) Will try to do some tests to see if i can imprrove this through config ui . Will let this open for reference so for the moment.

**Comment by nicoduj** [comment]
made the text a bit more clear. In fact, in config UI, you must add each area one by one with no comma at all. the text was more for manual editing .
