### ISSUE TITLE
Is it possible to set the number of cleanings to two for a custom area?

### ISSUE THREAD

**Issue by MichaelPlank** [nicoduj/homebridge-deebotEcovacs#44]
Hi team,
is it possible to set the number of cleanings for a custom area to 2 instead of a single cleaning in the config?

so far I have:
"publishCustomAreaSwitches": [ "1600,6700,4500,10400" ]

Thx for this awesome plugin!!

**Comment by nicoduj** [comment]
Will add this to the backlog.

**Comment by DaveM8686** [comment]
> 
> 
> Hi team,
> is it possible to set the number of cleanings for a custom area to 2 instead of a single cleaning in the config?
> 
> so far I have:
> "publishCustomAreaSwitches": [ "1600,6700,4500,10400" ]
> 
> Thx for this awesome plugin!!

Hi @MichaelPlank, how did you find the coordinates for the custom area?  I'm struggling to figure that out.

**Comment by mrbungle64** [comment]
@DaveM8686 

https://github.com/mrbungle64/ecovacs-deebot.js/wiki/CustomArea#retrieve-coordinates-from-log-output

**Comment by DaveM8686** [comment]
> 
> 
> @DaveM8686
> 
> https://github.com/mrbungle64/ecovacs-deebot.js/wiki/CustomArea#retrieve-coordinates-from-log-output

Perfect, thanks so much!

**Comment by nicoduj** [comment]
should be possible in 1.4.5-beta.1
