### ISSUE TITLE
I think this plugin is crashinng my homebridge installation

### ISSUE THREAD

**Issue by MichaelPlank** [nicoduj/homebridge-deebotEcovacs#45]
Hi team,

unfortunately something is crashing my homebridge installation and I think it is related to the homebridge-deebotEcovacs plugin.

I found this in the /var/log/homebridge.log:
```
<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xee3360]
    1: StubFrame [pc: 0xe5b86c]
Security context: 0x3188ea21 <JSObject>
    2: refreshAllDeebots [0x33067cf1] [/usr/lib/node_modules/homebridge-deebotecovacs/index.js:849] [bytecode=0x540d0431 offset=136](this=0x5f48de45 <myDeebotEcovacsPlatform map = 0x50dae66d>)
    3: _onTimeout [0x4179dcf9] [/usr/lib/node_modules/homebridge-deebotecovacs/index.js:840] [bytecode=0x540d0795 offset=11](this=0x4179d869 <Tim...
```

Is this something you can help with?

I'm running on:

Node.js Version: v12.19.0
NPM version: v6.14.8
Homebridge: v1.1.6
homebridge-deebotecovacs: v1.4.1

**Comment by nicoduj** [comment]
Hi, can you post homebridge logs around the crash (if possible in debug mode ?)

**Comment by nicoduj** [comment]
Closing since I did not get the logs.
