### ISSUE TITLE
Icons remaining after uninstall plug-in

### ISSUE THREAD

**Issue by Stetocasa** [nicoduj/homebridge-deebotEcovacs#48]
Hello, yesterday the plug-in now worked with my Deboot 605, I used it for months without any problem.
Tried to remove the plug-in and reinstall but in HomeKit compare the oldest icons and the new one. How can clean up 100% of plug-in data to show HK without any icons?
Thanks
Stefano

**Comment by nicoduj** [comment]
Hi,
plugin is using cahed accessories. so, in homebridge, you have to clean the cache (you can do this easily using configUI-X)
