### ISSUE TITLE
Question: Create Custom Area Switch

### ISSUE THREAD

**Issue by Marfre888** [nicoduj/homebridge-deebotEcovacs#49]
Hi,

Firstly thank you for this project. It has been great to be able to get my Ecovacs into Homekit. I hope that in the future Apple will decide to support robot vacuums but in the meantime, this project perfectly handles any shortcomings.

My Ecovacs 950 has developed a weird problem where it randomly decides to only do the first 20% of my floor. This same behaviour is also experienced in the app, so in no way am I blaming this plugin.

However, what seems to fix this issue is if I run a custom area. However, I'm looking at the documentation of how to get map_position, but I'm struggling.

Could anyone please help me out?

Thanks

**Comment by nicoduj** [comment]
Hi,

it is something I must find time to work on. You can check this issue that would give a hint, but definitiely I could do better ; #38

**Comment by nicoduj** [comment]
linked to #39 - closing
