### ISSUE TITLE
Characteristic Error in Homebridge 1.3.0

### ISSUE THREAD

**Issue by Marfre888** [nicoduj/homebridge-deebotEcovacs#53]
Hi,

I'm beta testing Homebridge 1.3.0 (beta 58). The deebotecovacs plugin is producing this error, which does not seem to happen in 1.2.x

Is something wrong with my installation, or is this a bug?

![deebot](https://user-images.githubusercontent.com/63603736/108043426-61bea000-7041-11eb-9999-1440dfdc3983.PNG)

![ecovacs](https://user-images.githubusercontent.com/63603736/108044308-659ef200-7042-11eb-9ebb-f0f86b9a4e27.PNG)

**Comment by Marfre888** [comment]
![ecovacs](https://user-images.githubusercontent.com/63603736/108351510-eba76e00-71e5-11eb-8560-1b86ac2f62c0.PNG)

**Comment by Seidel76** [comment]
I've the same warning...

**Comment by nicoduj** [comment]
Hi, I have not tested the plugin in 1.3 yet. Will try to do it asap.
