### ISSUE TITLE
Deebot N79s Unresponsive Through the Home App v1.4.5-beta0-latest

### ISSUE THREAD

**Issue by dekay7** [nicoduj/homebridge-deebotEcovacs#55]
### Recreation: 
- Install the Homebridge Deebotecovacs v1.4.5-beta0-latest plugin
- Open the Home app and attempt to control your Deebot N79s

### Observed Result:
- Deebot does not execute any actions or any triggers through the Home app or accessory control

### Expected Result: 
- Deebot responds accordingly

### Relative Log Message:
```
[DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
[DeebotEcovacs] INFO - Discovered Deebot : S0M3TH1NG
[DeebotEcovacs] INFO - Edge Cleaning for S0M3TH1NG : true
[DeebotEcovacs] INFO - Spot Cleaning for S0M3TH1NG : true
[DeebotEcovacs] INFO - SpotArea Cleaning for S0M3TH1NG : false
[DeebotEcovacs] INFO - CustomArea Cleaning for S0M3TH1NG : false
```
(it doesn't actually say "S0M3TH1NG," but it gives the deebot code but like idk if that is confidential)...

### Occurrence: 
This issue is only occurring on the v1.4.5-beta0-latest version of the plugin, however, it works fine on version 1.4.4. 

**Additional Notes:** There is actually no error message in the logs. The plugin successfully identifies the device and configuration but simply does not function. Seems to also not display the accurate battery status (percentage or charging) it just says 0% battery and status: "not charging" even though it is charging on the dock. It operates perfectly in the Ecovacs app.

**Comment by REBELinBLUE** [comment]
Getting this also, doesn't start the vacuum if I trigger it was from Homebridge-UI either

**Comment by dekay7** [comment]
So, from my understanding, neither controlling from the home app or the Homebridge accessory control is functioning on this version. Not only does it not start, but it doesn't beep either. Also, it doesn't receive status like charging and battery...

**Comment by REBELinBLUE** [comment]
Just downgraded to 1.4.4 and it works (hadn't actually realised there had been a new release until I saw this bug report)

**Comment by ahstram** [comment]
> Just downgraded to 1.4.4 and it works (hadn't actually realised there had been a new release until I saw this bug report)

Just set up my N79s and it wasn't working with the 1.4.5 beta either. Downgrading to 1.4.4 immediately solved the issue. Thanks!

**Comment by nicoduj** [comment]
Hi,

thank you for reporting. It was a beta on purpose :) Will try to release an new beta so that you can test. I think it is only on xmpp devices as far as I see.

**Comment by nicoduj** [comment]
Hi all,

could you test again in 1.4.5-beta.1 please ? thx

**Comment by bolducd** [comment]
My N79S is now working again with 1.4.5-beta.1. 

Thank you!

**Comment by deflao** [comment]
I have the same problem on current 1.4.5 and 1.4.6. Had to downgrade to 1.4.4 and everything works again. Hopefully it will be fixed soon

**Comment by nicoduj** [comment]
> I have the same problem on current 1.4.5 and 1.4.6. Had to downgrade to 1.4.4 and everything works again. Hopefully it will be fixed soon

Hi, could you please open a new issue since this one was closed, and give info about your model / conf please ? Thanks
