### ISSUE TITLE
No Deebot found 

### ISSUE THREAD

**Issue by Neueinsteiger** [nicoduj/homebridge-deebotEcovacs#56]
Hallo the Plugin doesnt find my Deebot, the other Deebot Plugin works. Whats wrong? 
tje log only Shows 0 Deebot found, trying again in one Minute. 
nothing Else. 
the Installation Shows the Same data Rhön the other Deebot Plugin. 
can you please help ne.

**Comment by ucsbricks** [comment]
@Neueinsteiger to help identify the issue, please post a comment on which Deebot Model you are using. Including the plugin config may be helpful too. As well as your Homebridge and homebridge-deebotEcovacs plugin versions.

**IMPORTANT: Please remember to replace any login data ("email" and "password") and other sensitive data with "XXXX" values before posting the JSON data here!!!**

**Comment by holger112** [comment]
Homebridge UI
homebridge-config-ui-x v4.39.1

homebridge-deebotecovacs v1.4.5-beta.0

I have an Deebot t8 aivi 

I've installed the Plugin Ober the configui. 
The other homebridge plug in named Deebot only works. 
Do you Need More Information?

**Comment by Neueinsteiger** [comment]
Homebridge UI
homebridge-config-ui-x v4.39.1

homebridge-deebotecovacs v1.4.5-beta.0

I have an Deebot t8 aivi

I've installed the Plugin Ober the configui.
The other homebridge plug in named Deebot only works.
Do you Need More Information?
My ecovacs Account works, i have the email adress and Passwort.

{
"email": "cxxxccc.hd@gmail.com",
"password": "Xxxxxxx!",
"countryCode": "DE",
"deebotNames": [
"Berta"
],
"refreshTimer": 30,
"publishBipSwitch": true,
"publishSwitch": true,
"publishFan": true,
"publishMotionDetector": true,
"publishAutoSwitch": true,
"publishEdgeSwitch": true,
"publishSpotSwitch": true,
"platform": "DeebotEcovacs"
}

**Comment by nicoduj** [comment]
Hi, can you try without any Name at first ? it might not be the good one. (don't filter using deebotNames property)

**Comment by Neueinsteiger** [comment]
Thank‘s a lot! Ot works. 
can you Tell how can i find the coordinate of a Custom cleaning area? 
does the t8 aivi dont Support Edge and Spot cleaning? 
my log Tell‘s me That Spot and Edge cleaning ist False.

**Comment by mrbungle64** [comment]
> Thank‘s a lot! Ot works.
> can you Tell how can i find the coordinate of a Custom cleaning area?

One option is to install the [ecovacs-deebot library](https://github.com/mrbungle64/ecovacs-deebot.js) and get the coordinates from the log:

1.)
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2.)
Edit `app2.js`
* Email/Ecovacs ID
* password

3.)
```bash
NODE_ENV=dev node app2.js | grep 'LastUsedAreaValues'
```

4.) Start a custom cleaning from mobile app

Then the coordinates are output in the log. For example:
```
[EcovacsMQTT_JSON] LastUsedAreaValues: -4498.000000,-1935.000000,-2814.000000,-3412.000000
```

> does the t8 aivi dont Support Edge and Spot cleaning?
> my log Tell‘s me That Spot and Edge cleaning ist False.

Spot and edge cleaning are not supported on the T8 series.

**Comment by ucsbricks** [comment]
@mrbungle64 thanks for the tutorial on how to obtain the coords. I wondered how to get them too.

**Comment by Neueinsteiger** [comment]
I Hope it is ok to ask the question here.
Is it possible to create a „go to“ Switch? And is It possible to stream the Video of the Deebot or Start the monitoring with HomeKit?

**Comment by nicoduj** [comment]
Hi, for the video if possible (don't know), it would involve a lot of work .
For go to I don't see any command for that.

I have only a basic deebot moreover so can't really play with such adavanced options.

**Comment by ThomasDevOps** [comment]
i also had a problem with this config and fixed it by removing the name var line:

{
    "name": "Deebot",   <----- remove this
    "countryCode": "BE",
    "username": "whatever@gmail.com",
    "password": "XXXXXXXXXXXXXXXXX",
    "platform": "Deebot"
}

**Comment by 52454D434F** [comment]
Hi all. I had the same issue " [DeebotEcovacs] INFO - no deebot found, will retry discovery in 1 minute". After reading the response from @ThomasDevOps  (https://github.com/nicoduj/homebridge-deebotEcovacs/issues/56#issuecomment-974809112) I emptied the nickname field in the plugin Settings: homebridge-deebotecovacs page. It immediately started to retrieve my Deebot info. There must be a bug with the name element in the config file. I hope they can resolve this. Saves hours of troubleshooting.
