### ISSUE TITLE
Can't connect to my deebot

### ISSUE THREAD

**Issue by ThatBFG** [nicoduj/homebridge-deebotEcovacs#58]
Hey,

Very new here and only just started playing around with Homebridge. I did install the deebotEcovacs plugin but when I restart, I get this message:

[3/18/2021, 11:11:00 PM] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: getaddrinfo ENOTFOUND portal-oc.ecouser.net
[3/18/2021, 11:11:00 PM] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute

Anybody has an idea what I'm doing wrong? 

I have the Deebot Ozmo 900

Cheers

**Comment by mrbungle64** [comment]
@ThatBFG 

`Error: getaddrinfo ENOTFOUND portal-oc.ecouser.net`
This error means that portal-oc.ecouser.net cannot be resolved or that it is not reachable.
Maybe there are some issues with your internet connection.

**Comment by ThatBFG** [comment]
I don't think so. I'm doing all kinds of things next to this little project.

**Comment by mrbungle64** [comment]
@ThatBFG 
It seams like `oc` is not valid as continent.
You can try `ww` as country code.

**Comment by ThatBFG** [comment]
thanks, tried this but result is the same 😟 

[3/19/2021, 12:33:55 AM] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: getaddrinfo ENOTFOUND eco-ww-api.ecovacs.com
[3/19/2021, 12:33:55 AM] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute

**Comment by ThatBFG** [comment]
here is the whole config:

"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "email": "xxx",
            "password": "xxx",
            "countryCode": "AU",
            "deebotNames": [
                "Alfred"
            ],
            "refreshTimer": 0,
            "publishBipSwitch": true,
            "publishSwitch": true,
            "publishFan": true,
            "publishMotionDetector": true,
            "publishAutoSwitch": true,
            "publishEdgeSwitch": true,
            "publishSpotSwitch": true,
            "platform": "DeebotEcovacs"
        }

**Comment by nicoduj** [comment]
Hi, Are you sure Alfred is the name of your deebot (same as mine, quite a coincidence :) )

**Comment by ThatBFG** [comment]
yeah, I'm sure.

I had a good chuckle when I stumbled over your plugin and saw the name of your deebot. Who wouldn't want to name their hoover "Alfred"?? It's just to fitting. No, I did not yet put a batman sticker onto it 😂

**Comment by ThatBFG** [comment]
I saw in another thread that you suggested to take the name out of the config, which I tried as well but same result as well

**Comment by mrbungle64** [comment]
@ThatBFG 

You can also try something like UK or ID as country code.

**Comment by ThatBFG** [comment]
HA, Thanks a lot!!! Changed the country code to UK and it works now like a charm.
