### ISSUE TITLE
no deebot found

### ISSUE THREAD

**Issue by handy80** [nicoduj/homebridge-deebotEcovacs#59]
Hey,
my DEEBOT OZMO 950 is not showing up in this plugin.
Any ideas what is not configured correctly?

Homebridge running as Docker on a Synology in Bridge-Mode.
- homebridge-deebotecovacs v1.4.5-beta.0 
- homebridge v1.3.4 

        {
            "email": "xxx@gmail.com",
            "password": "xxxxxxxx",
            "countryCode": "DE",
            "refreshTimer": 30,
            "publishBipSwitch": true,
            "publishSwitch": true,
            "publishFan": true,
            "publishMotionDetector": true,
            "publishAutoSwitch": true,
            "publishEdgeSwitch": false,
            "publishSpotSwitch": true,
            "platform": "DeebotEcovacs"
        }

**Comment by nicoduj** [comment]
Hi, could you sahre logs in debug ? did you try another country code ?

**Comment by smumriak** [comment]
My deebot n8 pro+ is detected, but controls do nothing. How to i get those debug logs?

UPD. nevermind, i realized you are talking about debug logs from homebridge itself

**Comment by smumriak** [comment]
```
[DeebotEcovacs] INFO - Error from deebot E02442600C09HGWY0315(ready : true) : Request Timeout
```
this is what i see

**Comment by nicoduj** [comment]
I suggest you try with the demo program of the lib I use - see https://github.com/nicoduj/homebridge-deebotEcovacs/issues/56#issuecomment-791510789

**Comment by mrbungle64** [comment]
@smumryak 

Please post the "class" value from Homebridge log first:

```
[15.5.2021, 18:37:02] [DeebotEcovacs] INFO - getDeebots : [{...,"class":"b2jqs4",...}}]
```

Should be something like `b2jqs4`

**Comment by smumriak** [comment]
hey @mrbungle64 
it's `85as7h` in my case

**Comment by mrbungle64** [comment]
> hey @mrbungle64
> it's `85as7h` in my case

There are now at least 10 different variants of the N8 😉 

@smumryak 
I added the N8 PRO+ to the config of the library.

@nicoduj 
It's available with version 0.6.1-alpha.9

**Comment by roficas** [comment]
I was never able to make this plugin work. I'm using the same user/pass I use for the app. Is that how I'm supposed to do? 
Logs:
```
[01/06/2021, 15:39:32] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: Failure code Incorrect account or password (1010) for call {func} and parameters {"account":"xxxx@gmail.com","password":"687...xxx...0a51"}
[01/06/2021, 15:39:32] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute
```

**Comment by nicoduj** [comment]
> I was never able to make this plugin work. I'm using the same user/pass I use for the app. Is that how I'm supposed to do?

Yes it should. Please post your conf (without login / pwd) and /or try different location

**Comment by roficas** [comment]
```
{
    "email": "xxx@gmail.com",
    "password": "xxx",
    "countryCode": "US",
    "deebotNames": [
        "Main",
        "Basement",
        "Upstairs"
    ],
    "refreshTimer": 0,
    "publishBipSwitch": true,
    "publishSwitch": true,
    "publishFan": true,
    "publishMotionDetector": true,
    "publishAutoSwitch": true,
    "publishEdgeSwitch": true,
    "publishSpotSwitch": true,
    "publishAreaSwitchesAsSeparateDevices": false,
    "showInfoLogs": false,
    "platform": "DeebotEcovacs"
}
```

Again, the user/pass is the same I just connected my iPhone app, but I still get the same authentication error. I can tell that the password I see in the logs is different from the one on the config (but I'm assuming encryption).

**Comment by nicoduj** [comment]
Will update the plugin today with latest 0.6.5 which should support this model, feel free to reopen

**Comment by roficas** [comment]
13/09/2021, 21:32:26] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: Failure code: Incorrect account or password (1010)
[13/09/2021, 21:32:26] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute

I double checked the password...

**Comment by mrbungle64** [comment]
@roficas 

Where is your location and where did you register your account?

**Comment by roficas** [comment]
I'm in the US and I registered using Ecovacs app...

**Comment by roficas** [comment]
you can close this ticket - I changed my password and now it works. I'm sorry for the inconvenience

**Comment by simonkfkwok** [comment]
May I know the details how it can work?  I still cannot connect my ECOVACS with HomeKit.  Thanks

**Comment by mrbungle64** [comment]
> May I know the details how it can work? I still cannot connect my ECOVACS with HomeKit. Thanks
> […](#)
> Sent from my iPhone
> On 9 Oct 2021, at 5:15 AM, roficas ***@***.***> wrote: ﻿ you can close this ticket - I changed my password and now it works. I'm sorry for the inconvenience — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

@smumriak 

I suggest that you create a new issue where you explain exactly what the problem is in your case.
As an alternative you can try [this](https://github.com/bwp91/homebridge-deebot) plugin.

Btw.: @nicoduj, are you still active here?

**Comment by nicoduj** [comment]
Hi, 

@mrbungle64  Indeed I am not a lot available. I can always do some update if needed but I don't check issues on a regular basics, sorry for that . Hope it will be better soon (btw thank you for checking and answering on this repo)
@smumriak open a New issue will be easier, I don't check closed one at all :)

**Comment by roficas** [comment]
> May I know the details how it can work? I still cannot connect my ECOVACS with HomeKit. Thanks
> […](#)

try going to their website and changing the password. That solved my issue (most likely to have a platform update on their side and I had a very old password there)
