### ISSUE TITLE
Plugin only works one time (cleaning routine)

### ISSUE THREAD

**Issue by snl1** [nicoduj/homebridge-deebotEcovacs#60]
Hi,

it seems the plugin only works one time (cleaning routine) in homebridge
e.g. The Deebot starts Cleaning in Spot Mode, finishes the cleaning and returns to the charging station. When i want to start another cleaning all the switches created by the plugin wont work until i restart the homebridge. After restarting they work like intended until another cleaning is finished and the Deebot returns to the charging station.
The ECOVACS app works without any problem, the deebot is still connected to the wlan.

i use homebridge 1.3.4 with this plugin (homebridge-deebotecovacs v1.4.5-beta.0) on Debian 10 and a Deebot Ozmo 950.

Config in Homebridge:
```
{
            "email": "xxx",
            "password": "xxx",
            "countryCode": "DE",
            "refreshTimer": 60,
            "publishBipSwitch": false,
            "publishSwitch": true,
            "publishFan": false,
            "publishMotionDetector": false,
            "publishAutoSwitch": true,
            "publishEdgeSwitch": false,
            "publishSpotSwitch": true,
            "publishSpotAreaSwitches": [
                "4",
                "3",
                "0",
                "1",
                "5",
                "2"
            ],
            "platform": "DeebotEcovacs"
        }
```

thanks for the help

**Comment by nicoduj** [comment]
Hi, the beta version have some trouble, I am aware but did not have time to work on this sorry. will do asap

**Comment by snl1** [comment]
hi, okay no problem, i will rollback to the 1.4.4 then. thank you!
