### ISSUE TITLE
Make Switches for Cleaning Modes Stateless

### ISSUE THREAD

**Issue by peter99330** [nicoduj/homebridge-deebotEcovacs#61]
Hi,

I have a suggestion for the implementation of the following switches in HomeKit

- publishAutoSwitch
- publishEdgeSwitch
- publishSpotSwitch
- publishSpotAreaSwitches
- publishCustomAreaSwitches

Sinne these switches turn right back off after turning them on (because they only trigger the start of an action), could they be exchanged for stateless switches (Stateless Programmable Switch)? I think it would make for a cleaner look, not sure about any possible drawbacks, though.

Let me know if you like the idea, I might even have some spare time after easter to work on it myself.

**Comment by nicoduj** [comment]
Hi, as far as I know programmable switch are made to activate other HomeKit devices so they would not be able to control the deebot / plugin.

**Comment by peter99330** [comment]
Hey, you are of course right. I had hoped the Stateless Switch would report back to the plugin when pushed from the Home App. I guess the current solution is the best possible one then.
