### ISSUE TITLE
Custom area very off

### ISSUE THREAD

**Issue by Glujaz** [nicoduj/homebridge-deebotEcovacs#62]
Hello,

First things first, thanks for your plug-in, really enjoying it. I have home bridge at home just for that (IKEA bridge is doing the rest for me).

I have a problem though (and I'm not talking about Apple's limitations here....)

I tried to do some custom areas. 4 to be precise. I used your library thing based of this wiki :
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/CustomArea#retrieve-coordinates-from-log-output

it seemed to be working fine, and got all my wished coordinates as shown in the attached image. 
![Capture d’écran 2021-04-19 à 20 10 27](https://user-images.githubusercontent.com/44747485/115314306-35282100-a175-11eb-8440-f856ff94b869.png)

But when running and checking inside the app, rather results are not right.
This is what I wanted him to do :
![413ADC51-8518-41CB-B285-4B20E42E8C48](https://user-images.githubusercontent.com/44747485/115314447-83d5bb00-a175-11eb-9dff-2ee3106dd8de.png)
And this is what I got
![3B2C4071-28A7-4EFB-847F-D78886FD0A36](https://user-images.githubusercontent.com/44747485/115314534-abc51e80-a175-11eb-8a94-37a04031e3ca.jpeg)

i think they are some coordinates problem somewhere...

for information, I have an Ozmo 905 (not 950). It has zones (but badly determined), and custom area capabilities.

thanks for your help ! :)

**Comment by nicoduj** [comment]
Hi, the underlying lib is all credits to @mrbungle64 . I think the issue should be reported there / you should try with his lib / sample to see if it is ok or not (I don't have such a deebot, so kinda blind when putting this in my plugin)

**Comment by Glujaz** [comment]
Ok. I was going to do new screenshots later today. They are not the real ones. I have to take my MacBook out and configure all this again to have the exact areas.

**Comment by mrbungle64** [comment]
@Glujaz 

> Ok. I was going to do new screenshots later today. They are not the real ones. I have to take my MacBook out and configure all this again to have the exact areas.

Please check this again if you can reproduce that behavior.

You can also add the follwing lines of code to app2.js file (for example in line 143) to check this:
```js
const areaValues = '-369,122,1352,2268';
vacbot.run('customArea', 'start', areaValues, 1);
```

Replace `'-369,122,1352,2268'` with your specific values you retrieved from `LastUsedAreaValues`.

**Comment by nicoduj** [comment]
By the way, on latest beta of my plugin, there is an option to write more info on zones , you can give it a try also.

**Comment by Glujaz** [comment]
Ok, so tried everything again. I'm looking to make the "kitchen" working first, as it is the most obvious not working. So the coordinates of that custom area is this (Thanks @nicoduj, the new debug feature works great !) : 
![Capture d’écran 2021-04-20 à 18 10 52](https://user-images.githubusercontent.com/44747485/115430285-86cbbc80-a204-11eb-8f88-4ec3f35ec8d1.png)

This, is based on this requested area in the Ecovacs app :

![IMG_1333](https://user-images.githubusercontent.com/44747485/115430533-bb3f7880-a204-11eb-82bb-33f13ada6660.PNG)

When selecting the switch in HomeKit, this is what I get in the Ecovacs app :
![IMG_1334](https://user-images.githubusercontent.com/44747485/115430692-e033eb80-a204-11eb-8c5e-483d7c19327d.PNG)

A (badly) made GIF shows the difference between the request and result :
![Bild](https://user-images.githubusercontent.com/44747485/115431013-2426f080-a205-11eb-8574-956d39b6e423.gif)

Hope this will help you better understand what's not working.

Last thing I tried was the command requested by @mrbungle64. And that one did worked. I definitely got what I asked :
<img width="768" alt="PNG-Bild" src="https://user-images.githubusercontent.com/44747485/115432212-6997ed80-a206-11eb-8506-4e374256b195.png">

This is what I added :
```
        const areaValues = '-4221.0,11767.0,-1315.0,9990.0';
        vacbot.run('customArea', 'start', areaValues, 1);
```

Last try I did, was removing the decimals, just in case. Did nothing in HomeKit.

So now, I assume it's more related to some code in your app @nicoduj :( (Sorry)

**Comment by mrbungle64** [comment]
@Glujaz 
@nicoduj 

Why are are there parentheses in the config?

```
"publishCustomAreaSwitches": [
        "['(1894.0,-424.0,-491.0,2950.0)']",
        "['(1946.0,4987.0,-1002.0,2931.0)']",
        "['(1582.0,4951.0,-1198.0,6928.0)']",
        "['(-4026.0,11583.0,-1183.0,9956.0)']",
        "['(-369.0,122.0,1352.0,2268.0)']"
```

**Comment by nicoduj** [comment]
That was a mistake in my readme, i have updated readme in latest beta, they should not be there . Should be something like this : 

```json
"publishCustomAreaSwitches": [
        "1894.0,-424.0,-491.0,2950.0",
        "1946.0,4987.0,-1002.0,2931.0",
        "1582.0,4951.0,-1198.0,6928.0",
        "-4026.0,11583.0,-1183.0,9956.0",
        "-369.0,122.0,1352.0,2268.0"]
```

**Comment by mrbungle64** [comment]
@Glujaz 

It should work properly if you remove the parentheses.

**Comment by Glujaz** [comment]
It worked ! 

Problem solved now !

[You know the song 😇](https://youtu.be/l8xUJY0-dDg)

thank you very much ! 😁
