### ISSUE TITLE
Canvas dependency

### ISSUE THREAD

**Issue by mrbungle64** [nicoduj/homebridge-deebotEcovacs#64]
Hi @nicoduj 

since version [4.20 ](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Changelog-(archive)#0420) of the library canvas is no longer required. I have moved canvas to the [optionalDependencies](https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/package.json) section.

I think that you can remove the warning in your plugin:

"IMPORTANT If you encounter any issue while installing, you might have to install additionnal packages on your environment since the main dependency of it depends on canvas library which is not available for all configurations. See there for more details : canvas compiling..."

**Comment by nicoduj** [comment]
Hi,

indeed ;) Homebridge / npm still put some warnings for this however during install last time I checked, that is why I wanted to take a look but completely forgot. thanks for putting an issue as a reminder !

**Comment by nicoduj** [comment]
Removed form changelog (still in readme but with a note that it is not necessary anymore since 1.2.0)
