### ISSUE TITLE
Unable to use CN based account

### ISSUE THREAD

**Issue by snhoi** [nicoduj/homebridge-deebotEcovacs#66]
Hi, I am using an account in the CN region but got the following error. 

[DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: getaddrinfo ENOTFOUND eco-cn-api.ecovacs.com

**Comment by mrbungle64** [comment]
@snhoi 

It seams that you're using an older version of the plugin. Please upgrade to latest version.

**Comment by snhoi** [comment]
@mrbungle64 

I am using plugin version v1.4.5, which I think should be the latest. 

I have since restarted the homebridge and it is now able to detect the deebot. 

Thanks for looking into it!

**Comment by mrbungle64** [comment]
@snhoi

> it is not able to detect the deebot

You mean "... it is now able to detect the deebot", right? 😉 

I guess that you forgot to restart homebridge after upgrading to version 1.4.5

**Comment by snhoi** [comment]
Yes it is able to detect now, thanks :-)
