### ISSUE TITLE
Spot Cleaning switch not true although configured

### ISSUE THREAD

**Issue by bondskin** [nicoduj/homebridge-deebotEcovacs#68]
I acticated "publishSpotSwitch" but the log it remains as "false"

My config:
           "publishBipSwitch": true,
            "publishSwitch": true,
            "publishFan": false,
            "publishMotionDetector": true,
            "publishAutoSwitch": true,
            **"publishEdgeSwitch": false,
            "publishSpotSwitch": true,**
            "publishAreaSwitchesAsSeparateDevices": true,

Homebridge log:
[14/05/2021, 16:18:36] [DeebotEcovacs] INFO - Edge Cleaning for Frau Kleinert : false
[**14/05/2021, 16:18:36] [DeebotEcovacs] INFO - Spot Cleaning for Frau Kleinert : false
[14/05/2021, 16:18:36] [DeebotEcovacs] INFO - SpotArea Cleaning for Frau Kleinert : true
[14/05/2021, 16:18:36] [DeebotEcovacs] INFO - CustomArea Cleaning for Frau Kleinert : true**

**Comment by mrbungle64** [comment]
@bondskin 

It seems that the model does not support Spot Cleaning.
What model do you own?

**Comment by bondskin** [comment]
Deebot 950

And I can see a map with the various rooms and they also have a map Id. Is that not spot cleaning?

**Comment by mrbungle64** [comment]
@bondskin 

> Deebot 950
> 
> And I can see a map with the various rooms and they also have a map Id. Is that not spot cleaning?

No, this is **SpotArea** Cleaning. The OZMO 950 does not support Spot Cleaning.

**Comment by bondskin** [comment]
Damn. Thx!

**Comment by bondskin** [comment]
last question, if I may, please @mrbungle64 

During extended mode the Deebot created a map of my home with rooms, I can see that also in the logs.
Example:
[15/05/2021, 09:32:43] [DeebotEcovacs] INFO - MapSpotAreaInfo {"mapID":"406969372","mapSpotAreaID":"6","mapSpotAreaName":"Kitchen","mapSpotAreaConnections":"3","mapSpotAreaBoundaries":"11000,-600;11000,0;11100,0;12050,950;12250,1000;12900,1550;12800,1400;12950,1300;13000,1050;13000,-650;12900,-700;12750,-600;11000,-600"} for Frau Kleinert

Is there any way that I can get a virtual homekit switch to start a cleaning of such a room?
Obviously Spot Area cleaning is not the right approach.
Would that be "CustomArea Cleaning Switches"?
But I am not sure how such a config would look like and if this would work?

**Comment by mrbungle64** [comment]
@bondskin 

"SpotArea Cleaning" should still be the right approach.

You switched from "Standard A,B,C ..." naming (see [here](https://github.com/nicoduj/homebridge-deebotEcovacs/issues/67)) to labels like "Kitchen", right?
You can use the "mapSpotAreaID" to get the number of the spot area.

**Comment by nicoduj** [comment]
Hi,

don't have such deebot so my coding was kinda blind on this. Did you try publishSpotAreaSwitches ? (with the id in the log, 6 I think ? )

**Comment by bondskin** [comment]
Hi @nicoduj , thanks. As @mrbungle64 mentioned, the 950 model does not support SpotAreas (this was my first attempt, too)

**Comment by bondskin** [comment]
> @bondskin
> 
> "SpotArea Cleaning" should still be the right approach.
> 
> You switched from "Standard A,B,C ..." naming (see [here](https://github.com/nicoduj/homebridge-deebotEcovacs/issues/67)) to labels like "Kitchen", right?
> You can use the "mapSpotAreaID" to get the number of the spot area.

So I tried this and added several SpotArea IDs (4,0,5,2,6)
In Homekit just SpotArea 0 appears

**Comment by nicoduj** [comment]
Can you share the config you tried ?

**Comment by bondskin** [comment]
{
            "email": "xxx@gmail.com",
            "password": "yyy",
            "countryCode": "DE",
            "deebotNames": [
                "Frau Kleinert"
            ],
            "refreshTimer": 0,
            "publishBipSwitch": true,
            "publishSwitch": true,
            "publishFan": false,
            "publishMotionDetector": true,
            "publishAutoSwitch": true,
            "publishEdgeSwitch": false,
            "publishSpotSwitch": false,
            "publishSpotAreaSwitches": [
                "4,0,5,2,6"
            ],
            "publishAreaSwitchesAsSeparateDevices": true,
            "showInfoLogs": true,
            "platform": "DeebotEcovacs"
        }

**Comment by nicoduj** [comment]
```json
"publishSpotAreaSwitches": [
"4,0,5,2,6"
],
```

Will do 1 switch that will clean all the areas

```json
"publishSpotAreaSwitches": [
"4","0","5","2","6"
],
```
Will do 1 switch per area

**Comment by bondskin** [comment]
@mrbungle64 , man, that did the trick!
Strangely, adding the numbers in the plugin form does not work, adding the numbers with " does also not work.
Only adding them with "" directly in the JSON form worked for me.
thank you so much!
