### ISSUE TITLE
China version T9 AIVI

### ISSUE THREAD

**Issue by townsmcp** [nicoduj/homebridge-deebotEcovacs#73]
Hi,
I have installed the plugin but can’t connect. I have a Chinese version from AliExpress. With these versions there is no username used. Instead you use a code and password. Any way to get this working?
I have seen that T9 and Chinese versions are supported in the following - just wondering if you are using this library?
https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/README.md

**Comment by mrbungle64** [comment]
@townsmcp 

I need the follwing line with the `class` value from the log to check if your model is already supportet by the library:

```
[15.5.2021, 18:37:02] [DeebotEcovacs] INFO - getDeebots : [{...,"class":"b2jqs4",...}}]
```

Should be something like `b2jqs4`

**Comment by townsmcp** [comment]
@mrbungle64 i switched on logging from the config and get the following lines show up:
![B9FF82E7-A004-44D9-94C7-947B3EFC018C](https://user-images.githubusercontent.com/14061617/129264268-3f50a276-62fc-469f-8d5f-82b8dca31d18.jpeg)

**Comment by mrbungle64** [comment]
@townsmcp 

ok, I see ...

What's the full model name?

**Comment by mrbungle64** [comment]
@townsmcp 

Have you already tried if it's working with this plugin?

https://github.com/bwp91/homebridge-deebot

**Comment by townsmcp** [comment]
I bought from this link on AliExpress:
https://bit.ly/3AELgMQ
It’s called the Deebot T9 AIVI
In the logs, the only Info line. Could find is:
![03E96C78-3896-441D-B984-B7D5EA0B4C05](https://user-images.githubusercontent.com/14061617/129265934-bb8ea5ae-ad77-48c1-8fd2-0158e2beb68b.jpeg)

**Comment by townsmcp** [comment]
> @townsmcp
> 
> Have you already tried if it's working with this plugin?
> 
> https://github.com/bwp91/homebridge-deebot

Will give that one a try and report back

**Comment by townsmcp** [comment]
Oops, I had the wrong password set in the config for this plugin. Log file shows the following with the correct password:
![4EA5422F-AFF5-478D-8936-6EC22AF88244](https://user-images.githubusercontent.com/14061617/129267503-c8700507-9c02-407c-b856-736937733052.jpeg)

I installed the other plugin that you mentioned and that one does connect to the vac and publishes to HomeKit

**Comment by townsmcp** [comment]
Don’t know if this log file helps from the other plugin? I see it has the class value:
![C7A97589-81F4-400E-83FF-D73FDC659472](https://user-images.githubusercontent.com/14061617/129268106-5b8dd033-c13c-4853-9bdf-b9f28d8f921e.png)

**Comment by mrbungle64** [comment]
@townsmcp 

homebridge-deebot is using the current version of the library, but that model (class `8kwdb4`) is still not fully supported.
I'll add the model so that it'll have improved support in the future.

**Comment by nicoduj** [comment]
Seems it was added https://github.com/mrbungle64/ecovacs-deebot.js/commit/a02b73f9c96762903e832c0f191b40d4e7b9a66c -> closing for now
