### ISSUE TITLE
Deebot 500 Unresponsive Through the Home App v1.4.5 and v1.4.6

### ISSUE THREAD

**Issue by deflao** [nicoduj/homebridge-deebotEcovacs#77]
Recreation:
Install the Homebridge Deebotecovacs v1.4.5 and v1.4.6 plugin
Open the Home app and attempt to control your Deebot 500

Observed Result:
Deebot does not execute any actions or any triggers through the Home app or accessory control

Expected Result:
Deebot responds accordingly

Relative Log Message:
[13/09/2021, 22:08:29] [DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
[13/09/2021, 22:08:29] [DeebotEcovacs] INFO - Discovered Deebot : Sucker
[13/09/2021, 22:08:29] [DeebotEcovacs] INFO - Edge Cleaning for Sucker : true
[13/09/2021, 22:08:29] [DeebotEcovacs] INFO - Spot Cleaning for Sucker : true
[13/09/2021, 22:08:29] [DeebotEcovacs] INFO - SpotArea Cleaning for Sucker : false
[13/09/2021, 22:08:29] [DeebotEcovacs] INFO - CustomArea Cleaning for Sucker : false

Occurrence:
This issue is only occurring on the v1.4.5 and v1.4.6 of the plugin. However, it works fine on version 1.4.4.

Additional Notes: There is actually no error message in the logs. The plugin successfully identifies the device and configuration but simply does not function. Below are the messages that appeared after installing v1.4.5 and v1.4.6 of the plugin.
![IMG_2029](https://user-images.githubusercontent.com/90084270/133189132-45557d4a-2c1d-443d-a911-4399690d23de.png)
![IMG_2028](https://user-images.githubusercontent.com/90084270/133189145-1170b42c-fa3a-40c7-8cc1-d755d52da9c0.png)

**Comment by deflao** [comment]
Environment:
Node.js Version: 14.17.6
NPM Version: 7.23.0
Homebridge Version: 1.3.4
Homebridge Config UI X Plugin Version: 4.41.2
Operating System: Raspbian GNU/Linux Buster (10)

**Comment by mrbungle64** [comment]
@deflao 
Please try if it works when you reinstall the plugin.
I just updated the underlying library.

**Comment by deflao** [comment]
> @deflao
> Please try if it works when you reinstall the plugin.
> I just updated the underlying library.

Thank you, it’s working now
