### ISSUE TITLE
DEEBOT N79S/SE goes offline unexpectedly 

### ISSUE THREAD

**Issue by benbrookshire** [nicoduj/homebridge-deebotEcovacs#78]
Have both a DEEBOT N79S/SE and a N8 Pro. Both are usable via HomeKit, but I consistently see the N79S go offline when checking status in the HomeBridge UI “My Devices” tab, while the N8 stays consistently online. When the N79S goes offline here, I can no longer control (Go Charge or Clean) via the Home app. 

When checking the status in the ECOVACSHOME app, both devices show as online. 

If I restart HomeBridge, both devices come back online and are accessible again within HomeBridge and can be activated via the Home app. 

Anything I could try or logs I could share that may help diagnose?

**Comment by nicoduj** [comment]
Hi,

could you try executing them on different bridges ?
