### ISSUE TITLE
Amazon.de T9+ doesn't get detected

### ISSUE THREAD

**Issue by yregaieg** [nicoduj/homebridge-deebotEcovacs#79]
Hello,

I tried setting up the plugin with a newly purchased T9+ from amazon.de but the plugin is unable to detect the robot.

I tried with homebridge-deebot plugin, and there I am able to connect, but there is only very limited set of features. Is there anything I can help you with in order to better support my robot model ?

Thanks :)

**Comment by mrbungle64** [comment]
> Hello,
> 
> I tried setting up the plugin with a newly purchased T9+ from amazon.de but the plugin is unable to detect the robot.

For your model it is necessary that the plugin uses the latest version of the [ecovacs-deebot.js](https://github.com/mrbungle64/ecovacs-deebot.js) library.
I'll release version 0.7.0 soon. Currently it's still in beta.
After release, you will need to reinstall this plugin to use this.

> 
> I tried with homebridge-deebot plugin, and there I am able to connect, ...

The homebridge-deebot plugin is already using the beta version (0.7.0-beta.3) of the library.

> but there is only very limited set of features. Is there anything I can help you with in order to better support my robot model ?

What features are you missing?

**Comment by yregaieg** [comment]
> For your model it is necessary that the plugin uses the latest version of the [ecovacs-deebot.js](https://github.com/mrbungle64/ecovacs-deebot.js) library. I'll release version 0.7.0 soon. Currently it's still in beta. After release, you will need to reinstall this plugin to use this.

Perfect, if you need someone to do some early testing, I can definitely build from sources and install to give you feedback.

> The homebridge-deebot plugin is already using the beta version (0.7.0-beta.3) of the library.

That would indeed explain.

> What features are you missing?

For now, I find it odd that the information about the robot is shown in a humidity sensor and a motion sensor, I would expect something more custom / accurate to not influence any automation I have based on such "real" sensors and still get that kind of status overview on the robot.
I also didn't manage to setup areas / custom cleaning options... so the only action I have is to start/stop deebot, which always starts an automatic cleaning and tries to remap the whole house (taking a lot longer than it normally would to clean, and totally ignoring my area preferences ...)

**Comment by mrbungle64** [comment]
@yregaieg 

I just released version 0.7.0 of the library.
You can reinstall this plugin now. Your device should then work properly.

**Comment by nicoduj** [comment]
Hi, I have made an update to bump to 0.7.0 . Many thanks @mrbungle64
