### ISSUE TITLE
Can't Install using Homebridge Config UI X

### ISSUE THREAD

**Issue by mattson16** [nicoduj/homebridge-deebotEcovacs#8]
When trying to install the plugin i get an error.

npm ERR! Command failed: git clone --mirror -q https://github.com/nicoduj/sucks.js.git /root/.npm/_cacache/tmp/git-clone-0cf90daf/.git
npm ERR! /root/.npm/_cacache/tmp/git-clone-0cf90daf/.git: Permission denied

**Comment by oznu** [comment]
Updating npm will fix that issue.

```
sudo npm install -g npm
```

@nicoduj publishing your dependencies to npm would also prevent strange issues that occur with npm and git.

**Comment by nicoduj** [comment]
Hi, thanks for answering while I was sleeping @oznu :) I will move the dep, it is only a temporary solution since I had to fork a dep that is not maintained anymore and needed some fixes to work . Found another one that is maintained and should work, will move to it ASAP :)

**Comment by nicoduj** [comment]
@oznu : I moved to a lib that works great, but unfortunately can't install on your marvelous docker image because of canvas not prebuild for musl and not able to build on the image (probably because missing dep (Cairo / pango) : https://github.com/Automattic/node-canvas#compiling 

I think i might have find a way, testing by using -e PACKAGES=build-base,cairo-dev,jpeg-dev,pango-dev,giflib-dev,librsvg-dev .... But I fear it will prevent the plugin from being certified, right ?

**Comment by oznu** [comment]
That's fine. Just make it clear what's required in your README.

**Comment by oznu** [comment]
Something like:

---

For use in the [oznu/homebridge](https://github.com/oznu/docker-homebridge) Docker image (Alpine Linux) please add the following line to your `startup.sh` script and restart the container. You can edit this file in directly in the Homebride UI by selecting the drop down menu in the upper-right-corner and selecting *Startup Script*.

```
apk add build-base cairo-dev jpeg-dev pango-dev giflib-dev librsvg-dev
```

**Comment by mattson16** [comment]
Thank you @nicoduj and @oznu. Using the env variable directly with docker solved the issue of being able to install this plugin. I was able to install and my vacuum is now appearing in the home app!

**Comment by nicoduj** [comment]
@mattson16 could I ask what model you are using ? Feedback is welcommed, also on feature list I am thinking of

**Comment by mattson16** [comment]
Hey @nicoduj I am using the n79s. I tested it out very briefly, but it seems to be working right now. Pressing the switch had it start and turning the switch to off had the vacuum find its way back to the dock. If i run into any other problems i will continue to stay active on the issues page. Thanks for your work on this! My deebot was the last thing on my list i wanted to get working in Homekit!
