### ISSUE TITLE
Deebot ozom 930

### ISSUE THREAD

**Issue by TomekGsc** [nicoduj/homebridge-deebotEcovacs#80]
#Hello, I am using your deebotecovacs plugin. works ok but only for a while after homebridge reboot. I have to reset homebridge every day because it stops working. Plugin as a subordinate bridge doesn't help either. Homebridge put on raspberry pi, everything up to date. deebot ozom 930 .Where could the problem be?

**Comment by nicoduj** [comment]
Hi, could you provide logs (in debug) when it happens ? Seems to be a connection loss issue. If you use a subordinate bridge, is it working agin if you restart the bridge only ?

**Comment by TomekGsc** [comment]
hello i didn't try to reset the subbridge only. if there is something in the log, I will paste it. Thanks
#
