### ISSUE TITLE
Unable to Install or Uninstall Plugin

### ISSUE THREAD

**Issue by PBXLthrMan** [nicoduj/homebridge-deebotEcovacs#82]
I ran into an error when I tried to install the Plugin, I've tried to reinstall the plugin, no success. Now I can uninstall the plugin as well.

OS | Raspbian GNU/Linux Bullseye (11)
Node.js Version | v16.13.1
NPM Version | v8.3.0
homebridge-config-ui-x v4.41.5
homebridge-deebotecovacs v1.4.7

Trying to re-install the plugin:
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-deebotecovacs@1.4.7

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-deebotecovacs
npm ERR! dest /usr/local/lib/node_modules/.homebridge-deebotecovacs-KEfMQvaA
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-deebotecovacs' -> '/usr/local/lib/node_modules/.homebridge-deebotecovacs-KEfMQvaA'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-04T14_18_03_528Z-debug-0.log

Command failed. Please review log for details.

From the Status Log:
[04/01/2022, 08:34:50] ====================
[04/01/2022, 08:34:50] ERROR LOADING PLUGIN homebridge-deebotecovacs:
[04/01/2022, 08:34:50] Error: Cannot find module 'ecovacs-deebot'
Require stack:
- /usr/local/lib/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js
- /usr/local/lib/node_modules/homebridge-deebotecovacs/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[04/01/2022, 08:34:50] ====================

From the Uninstall Screen:

USER: pi
DIR: /usr/local
CMD: sudo -E -n npm uninstall -g homebridge-deebotecovacs

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-deebotecovacs
npm ERR! dest /usr/local/lib/node_modules/.homebridge-deebotecovacs-KEfMQvaA
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-deebotecovacs' -> '/usr/local/lib/node_modules/.homebridge-deebotecovacs-KEfMQvaA'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-04T14_13_26_872Z-debug-0.log

Command failed. Please review log for details.

**Comment by nicoduj** [comment]
Hi,

how are you trying to install / uninstall ? Is it through configUI-X ? semms like an npm / globall install problem, but as far as I know homebridge does not install the plugin globally.

**Comment by PBXLthrMan** [comment]
> Hi,
> 
> how are you trying to install / uninstall ? Is it through configUI-X ? semms like an npm / globall install problem, but as far as I know homebridge does not install the plugin globally.

HI @nicoduj , I'm trying to install/uninstall via the interface, nothing fancy.

**Comment by nicoduj** [comment]
Hum ok. You can try this then : https://github.com/homebridge/homebridge/issues/3037 (change the directory accordingly to your error :) )

**Comment by PBXLthrMan** [comment]
> Hum ok. You can try this then : [homebridge/homebridge#3037](https://github.com/homebridge/homebridge/issues/3037) (change the directory accordingly to your error :) )

That did it! Thanks @nicoduj !
