### ISSUE TITLE
Support Yeedi robots

### ISSUE THREAD

**Issue by apfelnutzer** [nicoduj/homebridge-deebotEcovacs#84]
I'm not sure if this is possible but the trademark "Yeedi" seems to be closely related to Ecovacs so it might be possible to support support Yeedi models as well, e.g. the Yeedi Mop Station?!

**Comment by mrbungle64** [comment]
@apfelnutzer 

Can you please try the following:

- Install homebridge-deebotEcovacs plugin
- Find the [plugin path](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux#configuration-reference) of Homebridge
- Replace 'ecovacs.com' with 'yeedi.com' in the file [plugin path]/ecovacs-deebot/library/ecovacsConstants.js
- Use your Yeedi account credentials to set up the plugin
- You may need to restart Homebridge before it can work

**Comment by mrbungle64** [comment]
@apfelnutzer 

I'm the developer of the [underlying library](https://github.com/mrbungle64/ecovacs-deebot.js).
If it works, I can also support some Yeedi models.
I don't own a Yeedi, so I can't check it myself.

**Comment by apfelnutzer** [comment]
@mrbungle64 Thanks for your response! I'll get back to you as soon as possible, hopefully this weekend.

**Comment by apfelnutzer** [comment]
@mrbungle64 I made the following adjustments to `ecovacConstants.js`:

```
diff ecovacsConstants.js.old ecovacsConstants.js
8c8
< exports.MAIN_URL_FORMAT = 'https://gl-{country}-api.ecovacs.com/v1/private/{country}/{lang}/{deviceId}/{appCode}/{appVersion}/{channel}/{deviceType}';
---
> exports.MAIN_URL_FORMAT = 'https://gl-{country}-api.yeedi.com/v1/private/{country}/{lang}/{deviceId}/{appCode}/{appVersion}/{channel}/{deviceType}';
11c11
< exports.PORTAL_GLOBAL_AUTHCODE = 'https://gl-{country}-openapi.ecovacs.com/v1/global/auth/getAuthCode';
---
> exports.PORTAL_GLOBAL_AUTHCODE = 'https://gl-{country}-openapi.yeedi.com/v1/global/auth/getAuthCode';
```

After configuring my account data and restarting homebridge I see the following error messages:

```
[6/1/2022, 6:26:33 AM] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: Failure code 0002: Parameter error. Please try again later.
[6/1/2022, 6:26:33 AM] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute
```

What about other domains in `ecovacsConstants.js` like `ecouser.net`?

**Comment by mrbungle64** [comment]
> @mrbungle64 I made the following adjustments to `ecovacConstants.js`:
> 
> ...
> 
> What about other domains in `ecovacsConstants.js` like `ecouser.net`?

Hi Sebastian,

the domain "ecouser.net" is correct.

We found out that some keys are different, but [the login works now](https://github.com/Ligio/hacc-ozmo/issues/38#issuecomment-1143345674) 😄 

After the login there's now a `Interface authentication failed` error. That's what we need to solve next ...

**Comment by mrbungle64** [comment]
@apfelnutzer 

You can also try the current development branch of the library if you like.
I just pushed another commit and hope that it finally works now 😉 

```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
git checkout 'alpha/0.8.3'
npm install
```

Follow the [setup instructions](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Example-apps#setup)

After that, please add "yeedi.com" as a domain in the settings file:
```js
exports.AUTH_DOMAIN = 'yeedi.com';
```

Then you can run the example app:
```
cd example
NODE_ENV=dev node ./app2.js
```

**Comment by apfelnutzer** [comment]
@mrbungle64 Thanks a lot! :-) I'll give it a try this evening. I'm running Homebridge in a docker container, but as far as I know the plugins are installed separately so it should be possible to check out the development branch instead (hopefully).

**Comment by apfelnutzer** [comment]
@mrbungle64 Ah, ok - just noticed that you suggested to start it separately - I'll try it out!

**Comment by mrbungle64** [comment]
@apfelnutzer 

> @mrbungle64 Ah, ok - just noticed that you suggested to start it separately - I'll try it out!

Ja genau 😃

**Comment by apfelnutzer** [comment]
@mrbungle64 I'm running into errors when executing `npm install`. The first time it said:

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

When I tried it again the following output was shown:

```
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> canvas@2.9.1 install /home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v64-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@10.24.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v64-linux-glibc-arm.tar.gz 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:349:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.63-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas
gyp ERR! node -v v10.24.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/home/sebastian/temp/ecovacs-deebot.js/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.10.63-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/sebastian/temp/ecovacs-deebot.js/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas
node-pre-gyp ERR! node -v v10.24.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/sebastian/temp/ecovacs-deebot.js/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN ws@7.5.7 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.7 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.9.1 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.9.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by mrbungle64** [comment]
@apfelnutzer 

The [minimum required version](https://github.com/mrbungle64/ecovacs-deebot.js#installation) for the library of Node.js is 12.x
v10.24.0 is very old and not supported anymore. You should upgrade Node.js 😉 
https://nodejs.org/en/about/releases/

**Comment by mrbungle64** [comment]
> @mrbungle64 I'm running into errors when executing `npm install`. The first time it said:
> 
> ```
> npm ERR! cb() never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> ```
> 

If this error occurs again, you can try the following:

```
npm cache clean -force
```

**Comment by mrbungle64** [comment]
@apfelnutzer 

Btw.: You don't necessarily need canvas to run the library. It is optional.
Please try without installing canvas.
But you need to upgrade Node.js

**Comment by apfelnutzer** [comment]
@mrbungle64 Updated nodejs to 16.x, `npm install` worked now - I will continue the test soon. Thanks for the hint!

**Comment by apfelnutzer** [comment]
@mrbungle64 I started `app.js` first and got the following error (mail address and password hash masked):

```
[EcovacsAPI] Setting up EcovacsAPI instance
[EcovacsAPI] Calling main api user/login with {"account":"***@***.com","password":"*****************"}
[EcoVacsAPI] callUserAuthApi calling https://gl-de-api.yeedi.com/v1/private/DE/EN/b97a8d790fd1cbe2e899e0952be8b57b/yd_global_e/1.3.0/google_play/1/user/login
[EcoVacsAPI] callUserAuthApi config account=***@***.com&password=*****************&authTimespan=1654241897446&requestId=44afe003176b456a5196f3d8609d0a74&authTimeZone=GMT-8&authAppkey=1581917520081&authSign=cbc3534e76ea0816ae8ec90ad7f69ae1
[EcoVacsAPI] callUserAuthApi data: {"code":"0000","msg":"操作成功","time":1654241897843,"data":{"uid":"20211213181455_996c6efbd1c9938a3ea03bc15f7e0fe5","accessToken":"5cd0c7a6cc1159227056233821fb207f","userName":"YADQBHRX","email":"***@***.com","mobile":null,"loginName":"***@***.com","ucUid":"20211213171455_17a3757ae8f9240b6d912b9f48d98768"},"success":true}
[EcovacsAPI] Calling main api user/getAuthCode with {"uid":"20211213181455_996c6efbd1c9938a3ea03bc15f7e0fe5","accessToken":"5cd0c7a6cc1159227056233821fb207f"}
[EcoVacsAPI] callUserAuthApi calling https://gl-de-openapi.yeedi.com/v1/global/auth/getAuthCode
[EcoVacsAPI] callUserAuthApi config uid=20211213181455_996c6efbd1c9938a3ea03bc15f7e0fe5&accessToken=5cd0c7a6cc1159227056233821fb207f&authTimespan=1654241898113&bizType=ECOVACS_IOT&deviceId=b97a8d790fd1cbe2e899e0952be8b57b&openId=global&authAppkey=1581923437995&authSign=76cd89b6b9a96ee85723c4c5b9e17cc1
[EcoVacsAPI] callUserAuthApi data: {"code":"0002","msg":"接口鉴权失败","time":1654241899656}
[EcoVacsAPI] callUserAuthApi error: Error: Failure code 0002: 接口鉴权失败
Failure in connecting: Failure code 0002: 接口鉴权失败
```

**Comment by apfelnutzer** [comment]
@mrbungle64 BTW: Just spotted "Google Play" in the output - I'm actually using the iOS app (not sure if this is relevant...).

**Comment by apfelnutzer** [comment]
@mrbungle64 According to Google Translate the Chinese message means "Interface authentication failed".

**Comment by mrbungle64** [comment]
@apfelnutzer 

ok, thanks for the information 👍🏻 
I need to further analyze where other differences are between the two APIs.

> BTW: Just spotted "Google Play" in the output - I'm actually using the iOS app (not sure if this is relevant...)

No, that's not relevant in this case.

**Comment by apfelnutzer** [comment]
@mrbungle64 Just curious: how are you doing this?

**Comment by apfelnutzer** [comment]
@mrbungle64 ... because I already asked Yeedi, if there'd be an API documentation available and they answered there'd be no API documentation available.

**Comment by apfelnutzer** [comment]
@mrbungle64 What does MIM traffic stand for? I already stumbled upon `mitmproxy` and thought it might be helpful to analyze the API calls but did not yet find any time to approach this...

**Comment by mrbungle64** [comment]
@apfelnutzer 

Feel free to contact me on Discord: mrbungle64#7093

**Comment by mrbungle64** [comment]
@apfelnutzer 
I deleted my post from 2 days ago with my discord username in it.
I assume that you received a notification mail with that information 😉

**Comment by mrbungle64** [comment]
@apfelnutzer 
I also made another small change.
You can checkout the "alpha/0.8.3" branch again and try it out if you like.

**Comment by apfelnutzer** [comment]
@mrbungle64 I did a `git pull` in the ecovacs-deebot directory and started `app.js` again - same result: error code 002 ("Interface authentication failed").

**Comment by mrbungle64** [comment]
@apfelnutzer 

> @mrbungle64 What does MIM traffic stand for?

MIM (traffic) stands for "Man in the middle" (traffic)

> I already stumbled upon `mitmproxy` and thought it might be helpful to analyze the API calls but did not yet find any time to approach this...

Do you think you can find the time now? 😉

**Comment by mrbungle64** [comment]
@apfelnutzer 

I would like to continue with the conversation in [this issue](https://github.com/mrbungle64/ecovacs-deebot.js/issues/175)

**Comment by apfelnutzer** [comment]
> @apfelnutzer 
> 
> 
> 
> > @mrbungle64 What does MIM traffic stand for?
> 
> 
> 
> MIM (traffic) stands for "Man in the middle" (traffic)
> 
> 
> 
> > I already stumbled upon `mitmproxy` and thought it might be helpful to analyze the API calls but did not yet find any time to approach this...
> 
> 
> 
> Do you think you can find the time now? 😉 

I'll get back to you via Discord today! Did not notice this message yesterday...
