### ISSUE TITLE
Start using area switches

### ISSUE THREAD

**Issue by dahcar** [nicoduj/homebridge-deebotEcovacs#87]
When starting using an area switch, my Deebot resumes the last room/area that was used. If I switch it again it will then go to the desired area. Is this an issue or am I doing something wrong?

**Comment by nicoduj** [comment]
Hi,

Could you provide some logs in debug mode ? My deebot does not have areas so it was some blind coding on this part ...

**Comment by dahcar** [comment]
I can’t get it to do it now. I will grab the logs if I can reproduce the issue.
