### ISSUE TITLE
Unable to reach service

### ISSUE THREAD

**Issue by Glujaz** [nicoduj/homebridge-deebotEcovacs#89]
Hi there again.

It's been working fine until last week. For whatever reason, Homebridge is not able anymore to get to the service. I get this error when connecting :

`[9/17/2022, 12:30:44 PM] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: getaddrinfo ENOTFOUND gl-fr-api.ecovacs.com`
`[9/17/2022, 12:30:44 PM] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute`

Any reasons why ?
I'm also taging @mrbungle64 who might also help.

Thanks in advance :)

**Comment by mrbungle64** [comment]
@Glujaz 

Have you already checked if you can reach the service with your Ecovacs mobile app (same network)?

**Comment by Glujaz** [comment]
Yes I did, and it’s working really fine !

**Comment by mrbungle64** [comment]
@Glujaz 

Seams that `gl-fr-api.ecovacs.com` is currently not available:

```bash
> ping gl-fr-api.ecovacs.com
PING global-app-eu-288285937.eu-central-1.elb.amazonaws.com (3.127.17.79) 56(84) Bytes Daten.
```

**Comment by Glujaz** [comment]
Yeah, same issue on my computer.

I restarted my server (not just homebridge) though, and it seems to work fine again... No Idea why...

Thanks a lot anyway :)

**Comment by Glujaz** [comment]
Ok, so there is a problem again, where it says the robot is unreachable...

It's an Ozmo 905. @mrbungle64 do you think it's because of your unsupported list mentioned on your script ?

**Comment by mrbungle64** [comment]
> Ok, so there is a problem again, where it says the robot is unreachable...
> 
> It's an Ozmo 905. @mrbungle64 do you think it's because of your unsupported list mentioned on your script ?

@Glujaz 
No, it's not an "unsupported list" - it's a list of "Legacy models".
These models should normally still work with my library (not a script)

**Comment by Glujaz** [comment]
Ok, sorry, i solved this in the most stupidest way : putting it back its base station... it did not charge when it went back on it. So problem solved now 🤦‍♂️

and thanks for your reply, I feel relieved. I though initially that it would stop being supported...
