### ISSUE TITLE
Publish SpotArea Cleaning Switches not being generated

### ISSUE THREAD

**Issue by eenduiker** [nicoduj/homebridge-deebotEcovacs#91]
Hi, i have version 1.4.8 intergrated with Homebridge and HomeKit. All seems to work fine expect the publishing of SpotArea Switches.

SpotArea "0" is being created the "/AreaName" syntax is not being detected. The AreaName remains 0.
All other configured SpotArea are not being processed and do not show up in the LogFiles. Also not avaible in HomeBridge or HomeKit.

Current Config is "0,1,2,3" in the settings.

Some things about my Deebot T9 AIVI that might be of interest:
- I only have one Robot
- Robot has three maps associated with it: Basement, Floor Level & Upstairs.
- After initial auto Map and Area detection I modified the Areas to reflect my preferences via the Ecovacs App.

Below my log file starting from a restart:

[homebridge.log(3).txt](https://github.com/nicoduj/homebridge-deebotEcovacs/files/9645806/homebridge.log.3.txt)

**Comment by deandre** [comment]
I also had an issue with this — this [comment](https://github.com/nicoduj/homebridge-deebotEcovacs/issues/43#issuecomment-740484897) helped. Basically, alter your configuration as such (of course, replacing your own values):

```
...
            "publishSpotAreaSwitches": [
                "0/UtilityRoom",
                "3/Bedroom",
                "5/GuestBedroom",
                "8/Lounge"
            ],
...
```

EDIT: Spot areas refer to a sort of grouping of custom areas. It's not clear in the UI but pressing that orange button in that section adds additional areas. With your current configuration, there's only one spot area which then reflects accordingly in the Home app.

**Comment by eenduiker** [comment]
Thanks @deandre 🥇. I got it working based on your advice. I also understand the configuration much better now. The grouping is valuable to me as well. It wasn't clear to me earlier. Also didn't even realize the text is clickable. 🤦‍♂️ 
PS. its purple in my interface. :)
